CREATE TABLE users
(
    uid UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE items
(
    uid UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    root_uid UUID REFERENCES items (uid) ON DELETE CASCADE NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT current_timestamp,
    extension VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    is_favorites BOOLEAN DEFAULT FALSE,
    link BOOLEAN NOT NULL DEFAULT FALSE,
    size VARCHAR(255) NOT NULL DEFAULT '0',
    trash BOOLEAN NOT NULL DEFAULT FALSE
);

