DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS files CASCADE;

DROP TABLE IF EXISTS directories CASCADE;

DROP TABLE IF EXISTS link CASCADE;

DROP TABLE IF EXISTS link_directories CASCADE;

DROP TABLE IF EXISTS link_files CASCADE;

DROP TABLE IF EXISTS reсent CASCADE;

DROP TABLE IF EXISTS trash CASCADE;

DROP TABLE IF EXISTS trash_directories CASCADE;

DROP TABLE IF EXISTS trash_files CASCADE;